MovieCoreApp/MovieApp.UI/Controllers/TheatreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class TheatreController : Controller
    {

        IConfiguration _configuration;
        public TheatreController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [HttpGet]
        public async Task<IActionResult> ShowTheatreDetails()
        {

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
              
                // StringContent content = new StringContent(JsonConvert.SerializeObject(theatreInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Theatre/SelectTheatres";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<IEnumerable<TheatreModel>>(result);

                        return View(theatreModel);
                     
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Theatre entries!";
                    }
                }
            }

            return View();
        }

        public IActionResult TheatreRegister()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TheatreRegister(TheatreModel theatreModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Theatre/Register";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Register successfully!";  
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditTheatre(int theatreId)
        {
           
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                //  StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Theatre/SelectTheatreById?theatreId=" + theatreId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result); // getting only single record of usermodel

                        return View(theatreModel);
                       
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong theatre entries!";
                    }
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditTheatre(TheatreModel theatreModel)
        {
            
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
               
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Theatre/UpdateTheatre";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                       
                        ViewBag.Status = "Ok";
                        ViewBag.message = " Theatre updated! ";

                        //return View(theatreModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong theatre entries!";
                    }
                }
            }

            return View();
        }

        public async Task<IActionResult> Delete(int theatreId)
        {

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebAPiURL"] + "Theatre/SelectTheatreById?theatreId="+theatreId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result);


                        // UserModel userModel = result;

                        //ViewBag.Status = "Ok";
                        //ViewBag.message = " user Deleted! ";

                        return View(theatreModel);

                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(TheatreModel theatreModel)
        {


            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebAPiURL"] + "Theatre/DeleteTheatre?theatreId="+theatreModel.TheatreId;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        

                        ViewBag.Status = "Ok";
                        ViewBag.message = " Theatre Deleted! ";

                        return View(theatreModel);

                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong theatre entries!";
                    }
                }
            }

            return View();
        }


    }
}

MovieCoreApp/MovieApp.UI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;


namespace MovieApp.UI.Controllers
{
    public class UserController : Controller
    {
        IConfiguration _configuration;
        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> ShowUserDetails()
        {
            //Fetch API,Axios Api, HTTPClient
            //HTTP Req/response

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                // api url- http://localhost:5000/api/User/SelectUsers // (endpoint url)congigure this api url in upsetting file in MovieApp.UI
                // StringContent content = new StringContent(JsonConvert.SerializeObject(userInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "User/SelectUsers";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<IEnumerable<UserModel>>(result);

                        //var userModel= JsonSerializer.Deserialize<List<UserModel>>(result);
                        // UserModel userModel = result;
                        //object->JSON->http POST
                        //object<-JSON<-HTTP GET
                        // ViewBag.Status = "Ok";
                        //ViewBag.message = " user details succesfully";

                        return View(userModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

        public IActionResult UserRegister()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserRegister(UserModel userModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "User/Register";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Register successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }

        public IActionResult UserLogin()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UserLogin(UserModel userModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "User/Login";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = " Login Successfully";
                    }
                    // return RedirectToAction("Index", "Movies");
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong credentials!";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> EditUser(int userId)
        {
            //Fetch API,Axios Api, HTTPClient
            //HTTP Req/response

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                // api url- http://localhost:5000/api/User/SelectUsers // (endpoint url)congigure this api url in upsetting file in MovieApp.UI
                //  StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "User/SelectUserById?userId=" + userId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result); // getting only single record of usermodel

                        //var userModel= JsonSerializer.Deserialize<List<UserModel>>(result);
                        // UserModel userModel = result;
                        //object->JSON->http POST
                        //object<-JSON<-HTTP GET
                        // ViewBag.Status = "Ok";
                        //ViewBag.message = " user details succesfully";

                        return View(userModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserModel userModel)
        {
            //Fetch API,Axios Api, HTTPClient
            //HTTP Req/response

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                // api url- http://localhost:5000/api/User/SelectUsers // (endpoint url)congigure this api url in upsetting file in MovieApp.UI
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "User/UpdateUser";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        //var result = await response.Content.ReadAsStringAsync();
                        //var userModel = JsonConvert.DeserializeObject<UserModel>(result); // getting only single record of usermodel

                        //var userModel= JsonSerializer.Deserialize<List<UserModel>>(result);
                        // UserModel userModel = result;
                        //object->JSON->http POST
                        //object<-JSON<-HTTP GET
                        ViewBag.Status = "Ok";
                        ViewBag.message = " user updated! ";

                        //return View(userModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

      
        public async Task<IActionResult> Delete(int userId)
        {

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

              string endPoint = _configuration["WebAPiURL"] + "User/SelectUserById?userId="+ userId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result);


                        // UserModel userModel = result;

                        //ViewBag.Status = "Ok";
                        //ViewBag.message = " user Deleted! ";

                        return View(userModel);

                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserModel userModel)
        {
            

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                string endPoint = _configuration["WebAPiURL"] + "User/DeleteUser?userId="+userModel.UserId;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        //var result = await response.Content.ReadAsStringAsync();

MovieCoreApp/MovieApp.UI/Views/Theatre/Delete.cshtml
@model MovieApp.Entity.TheatreModel;
@{
    ViewData["Title"] = "DeleteTheatre";
}

<a asp-action="ShowTheatreDetails" asp-controller="Theatre">Theatre Details</a>
<hr/>
<h2>Delete Theatre</h2>
<form   method="post">
     <div class="form-group">
        <label for="UserId">TheatreId</label>
        <input type="text" class="form-control" asp-for="TheatreId" disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreName</label>
        <input type="text" class="form-control" asp-for="TheatreName" disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreCapacity</label>
        <input type="text" class="form-control" asp-for="TheatreCapacity"disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreType</label>
        <input type="text" class="form-control" asp-for="TheatreType"disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Firstname">TheatreLocation</label>
        <input type="text" class="form-control" asp-for="TheatreLocation" disabled="disabled"/>
    </div>
   
    <input type="submit" class="btn btn-primary" value="Delete">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="User" asp-action="UserLogin">Login</a>
</form>

MovieCoreApp/MovieApp.UI/Views/Theatre/EditTheatre.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "EditTheatre";
}

<a asp-action="ShowTheatreDetails" asp-controller="Theatre">Theatre Details</a>
<hr />
<h2>Edit-Theatre</h2>
<form method="post">
    <div class="form-group">
        <label>TheatreName</label>
        <input type="text" class="form-control" asp-for="TheatreName"/>
    </div>
    <div class="form-group">
        <label>TheatreCapacity</label>
        <input type="text" class="form-control" asp-for="TheatreCapacity"/>
    </div>
     <div class="form-group">
        <label>TheatreType</label>
        <input type="text" class="form-control" asp-for="TheatreType"/>
    </div>
     <div class="form-group">
        <label>TheatreLocation</label>
        <input type="text" class="form-control" asp-for="TheatreLocation"/>
    </div>
    <input type="submit" value="Update" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-primary" />
</form>
@if (ViewBag.status== "Ok")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status== "Error")

{
    <div class="alert alert-danger">@ViewBag.message</div>
    
}

MovieCoreApp/MovieApp.UI/Views/Theatre/ShowTheatreDetails.cshtml
@model IEnumerable<MovieApp.Entity.TheatreModel>
@{
    ViewData["Title"] = "ShowTheatreDetails";
}

<h2>ShowTheatreDetails</h2>
<hr />

    <table class="table table-bordered bg-light">
       <thead>
         <tr>
           <th>TheatreId</th>
           <th>TheatreName</th>
           <th>TheatreCapacity</th>
           <th>TheatreType</th>
           <th>TheatreLocation</th>
           <th>Edit</th>
           <th>Delete</th>
          </tr>
      </thead>
         
    <tbody>
         @foreach(var item in Model)
         {
         <tr>
         <td>@item.TheatreId</td>
          <td>@item.TheatreName</td>
           <td>@item.TheatreCapacity</td>
           <td>@item.TheatreType</td>
            <td>@item.TheatreLocation</td>
            <td><a asp-action="EditTheatre"  asp-route-TheatreId=@item.TheatreId>Edit</a></td>
            <td><a asp-action="Delete"  asp-route-TheatreId=@item.TheatreId>Delete</a></td>
         </tr>
         }
         </tbody>
         </table>

MovieCoreApp/MovieApp.UI/Views/Theatre/TheatreRegister.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "TheatreRegister";
}

<a asp-action="ShowTheatreDetails" asp-controller="Theatre">Theatre Details</a>
<hr />
<h2>TheatreRegister</h2>
<form method="post">
    <div class="form-group">
        <label>TheatreName</label>
        <input type="text" class="form-control" asp-for="TheatreName"/>
    </div>
    <div class="form-group">
        <label>TheatreCapacity</label>
        <input type="text" class="form-control" asp-for="TheatreCapacity"/>
    </div>
     <div class="form-group">
        <label>TheatreType</label>
        <input type="text" class="form-control" asp-for="TheatreType"/>
    </div>
     <div class="form-group">
        <label>TheatreLocation</label>
        <input type="text" class="form-control" asp-for="TheatreLocation"/>
    </div>
    <input type="submit" value="Register" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-primary" />
</form>
@if (ViewBag.status== "Ok")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status== "Error")

{
    <div class="alert alert-danger">@ViewBag.message</div>
    
}