MovieCoreApp/MovieApp.UI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class MovieController : Controller
    {
        IConfiguration _configuration;
        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> ShowMovieDetails()
        {
            //Fetch API,Axios Api, HTTPClient
            //HTTP Req/response

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                // api url- http://localhost:5000/api/Movie/SelectMovies // (endpoint url)congigure this api url in upsetting file in MovieApp.UI
                // StringContent content = new StringContent(JsonConvert.SerializeObject(userInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Movie/SelectMovies";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieModel = JsonConvert.DeserializeObject<IEnumerable<MovieModel>>(result);

                        //var userModel= JsonSerializer.Deserialize<List<MovieModel>>(result);
                        //  MovieModel movieModel = result;
                        //object->JSON->http POST
                        //object<-JSON<-HTTP GET
                        // ViewBag.Status = "Ok";
                        //ViewBag.message = " movie details succesfully";

                        return View(movieModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong movie entries!";
                    }
                }
            }

            return View();
        }

        public IActionResult MovieRegister()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MovieRegister(MovieModel movieModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Movie/Register";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie register successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }

        public IActionResult MovieLogin()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MovieLogin(MovieModel movieModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Movie/Login";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie entry Present";
                    }
                    // return RedirectToAction("Index", "Movies");
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "No such movie present!";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> EditMovie(int movieId)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                //  StringContent content = new StringContent(JsonConvert.SerializeObject(movieModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Movie/SelectMovieById?movieId=" + movieId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieModel = JsonConvert.DeserializeObject<MovieModel>(result); 

                        return View(movieModel);
                    
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong movie entries!";
                    }
                }
            }

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> EditMovie(MovieModel movieModel)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebAPiURL"] + "Movie/UpdateMovie";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        //var result = await response.Content.ReadAsStringAsync();
                        //var movieModel = JsonConvert.DeserializeObject<MovieModel>(result); // getting only single record of usermodel

                        //var movieModel= JsonSerializer.Deserialize<List<MovieModel>>(result);
                        // MovieModel movieModel = result;
                        //object->JSON->http POST
                        //object<-JSON<-HTTP GET
                        ViewBag.Status = "Ok";
                        ViewBag.message = " Movie updated! ";

                        //return View(movieModel);
                        // return RedirectToAction("Index", "Movies");
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong movie entries!";
                    }
                }
            }

            return View();
        }

        public async Task<IActionResult> Delete(int movieId)
        {

            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebAPiURL"] + "Movie /SelectMovieById?movieId=" + movieId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieModel = JsonConvert.DeserializeObject<MovieModel>(result);


                        // UserModel userModel = result;

                        //ViewBag.Status = "Ok";
                        //ViewBag.message = " user Deleted! ";

                        return View(movieModel);

                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong user entries!";
                    }
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(MovieModel movieModel)
        {


            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebAPiURL"] + "Movie/DeleteMovie?movieId=" + movieModel.MovieId;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        //var result = await response.Content.ReadAsStringAsync();
                        //var movieModel = JsonConvert.DeserializeObject<MovieModel>(result); // getting only single record of movieModel

                        //var movieModel= JsonSerializer.Deserialize<List<MovieModel>>(result);
                        // MovieModel movieModel = result;

                        ViewBag.Status = "Ok";
                        ViewBag.message = " Movie Deleted! ";

                        //return View(movieModel);

                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Movie entries!";
                    }
                }
            }

            return View();
        }

    }
}

MovieCoreApp/MovieApp.UI/Views/Movie/Delete.cshtml
@model MovieApp.Entity.MovieModel;
@{
    ViewData["Title"] = "DeleteMovie";
}

<a asp-action="showMovieDetails" asp-controller="Movie">Movie Details</a>
<hr/>
<h2>Delete Movie</h2>
<form   method="post">
     <div class="form-group">
        <label for="MovieId">MovieId</label>
        <input type="text" class="form-control" asp-for="MovieId" disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Moviename">Moviename</label>
        <input type="text" class="form-control" asp-for="Moviename" disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Movietype">Movietype</label>
        <input type="text" class="form-control" asp-for="Movietype"disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="MovieDescription">MovieDescription</label>
        <input type="text" class="form-control" asp-for="MovieDescription"disabled="disabled"/>
    </div>
    <div class="form-group">
        <label for="Movielangauge">Movielangauge</label>
        <input type="text" class="form-control" asp-for="Movielangauge" disabled="disabled"/>
    </div>
   
    <input type="submit" class="btn btn-primary" value="Delete">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="Movie" asp-action="MovieLogin">Login</a>
</form>

MovieCoreApp/MovieApp.UI/Views/Movie/EditMovie.cshtml
@model MovieApp.Entity.MovieModel;
@{
    ViewData["Title"] = "EditMovie";
}

<a asp-action="showMovieDetails" asp-controller="Movie">Movie Details</a>
<hr/>
<h2>Edit-Movie</h2>
<form method="post">
    <div class="form-group">
        <label for="Moviename">Moviename</label>
        <input type="text" class="form-control" asp-for="Moviename">
    </div>
    <div class="form-group">
        <label for="Movietype">Movietype</label>
        <input type="text" class="form-control" asp-for="Movietype">
    </div>
    <div class="form-group">
        <label for="MovieDescription">MovieDescription</label>
        <input type="text" class="form-control" asp-for="MovieDescription">
    </div>
    <div class="form-group">
        <label for="Movielangauge">Movielangauge</label>
        <input type="text" class="form-control" asp-for="Movielangauge">
    </div>
   
    <input type="submit" class="btn btn-primary" value="Update">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="Movie" asp-action="MovieLogin">Login</a>
</form>

MovieCoreApp/MovieApp.UI/Views/Movie/MovieLogin.cshtml
@model MovieApp.Entity.MovieModel;
@{
    ViewData["Title"] = "MovieLogin";
}

<h2>Movie-Login</h2>
<hr />
<form method="post">
    <div class="form-group">
        <label for="Firstname">MovieId</label>
        <input type="text" class="form-control" asp-for="MovieId">
    </div>
    <div class="form-group">
        <label for="Firstname">Moviename</label>
        <input type="text" class="form-control" asp-for="Moviename">
    </div>
    <input type="submit" class="btn btn-primary" value="Login">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="Movie" asp-action="MovieRegister">Register</a>
</form>

MovieCoreApp/MovieApp.UI/Views/Movie/MovieRegister.cshtml
@model  MovieApp.Entity.MovieModel;
@{
    ViewData["Title"] = "MovieRegister";
}

<h2>Movie-Register</h2>
<form method="post">
    <div class="form-group">
        <label for="Firstname">Moviename</label>
        <input type="text" class="form-control" asp-for="Moviename">
    </div>
    <div class="form-group">
        <label for="Firstname">Movietype</label>
        <input type="text" class="form-control" asp-for="Movietype">
    </div>
    <div class="form-group">
        <label for="Firstname">MovieDescription</label>
        <input type="text" class="form-control" asp-for="MovieDescription">
    </div>
    <div class="form-group">
        <label for="Firstname">Movielangauge</label>
        <input type="text" class="form-control" asp-for="Movielangauge">
    </div>
    
    <input type="submit" class="btn btn-primary" value="Register">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="Movie" asp-action="MovieLogin">MovieLogin</a>
    <a asp-controller="User" asp-action="UserLogin">UserLogin</a>
</form>

MovieCoreApp/MovieApp.UI/Views/Movie/ShowMovieDetails.cshtml
@model  IEnumerable<MovieApp.Entity.MovieModel>
@{
    ViewData["Title"] = "ShowMovieDetails";
}

<h3>ShowMovieDetails</h3>
<hr />

    <table class="table table-bordered bg-primary">
       <thead>
         <tr>
           <th>MovieId</th>
           <th>Moviename</th>
           <th>Movietype</th>
           <th>MovieDescription</th>
           <th>Movielangauge</th>
           <th>EditMovie</th>
           <th>DeleteMovie</th>
          </tr>
      </thead>
         
    <tbody>
         @foreach(var item in Model)
         {
         <tr>
         <td>@item.MovieId</td>
          <td>@item.Moviename</td>
           <td>@item.Movietype</td>
           <td>@item.MovieDescription</td>
            <td>@item.Movielangauge</td>
            <td><a asp-action="EditMovie"  asp-route-MovieId=@item.MovieId>EditMovie</a></td>
             <td><a asp-action="Delete"  asp-route-MovieId=@item.MovieId>DeleteMovie</a></td>
         </tr>
         }
         </tbody>
         </table>
 